### ISSUE TITLE
Missing items from NLeSc software checklist 

### ISSUE THREAD

**Issue by sonjageorgievska** [NLeSC/structure-from-motion#44]
The checklist is [here](https://guide.esciencecenter.nl/index.html). 

Items that I cannot find:

1. [x] Contribution guidelines (from 1.1. in the checklist) and a branching model in the contribution guidelines
2. [ ] Changelog for the releases (see 1.2)
3. [ ] Screencast in the NLeSc youtube channel (see 1.4)
4. [x] Code scrutinizer review

**Comment by sonjageorgievska** [comment]
The first and last item are resolved now, the changelog applies for the future. Screencast does not really apply.
